import { useRouter, type Href } from "expo-router";
import { useEffect, useState } from "react";

import { api } from "@/src/api/client";
import { supabase } from "@/src/lib/supabase";
import { BottomNav } from "@/src/components/bottom-nav";
import { DooLogo } from "@/src/components/doo-logo";
import {
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons, MaterialCommunityIcons } from "@expo/vector-icons";
import Animated, { FadeInDown } from "react-native-reanimated";
import * as Haptics from "expo-haptics";

import { colors, radius, spacing } from "@/src/theme/colors";

type IconLib = "ion" | "mci";

type ContextButton = {
  key: string;
  label: string;
  bg: string;
  textColor: string;
  iconColor: string;
  icon: string;
  lib: IconLib;
};

const CONTEXT_BUTTONS: ContextButton[] = [
  {
    key: "bus",
    label: "Je suis dans le bus",
    bg: colors.primary,
    textColor: colors.white,
    iconColor: colors.white,
    icon: "bus",
    lib: "ion",
  },
  {
    key: "pause",
    label: "Je suis en pause",
    bg: colors.secondary,
    textColor: colors.textDark,
    iconColor: colors.textDark,
    icon: "coffee-outline",
    lib: "mci",
  },
  {
    key: "lit",
    label: "Je suis dans mon lit",
    bg: colors.rose,
    textColor: colors.textDark,
    iconColor: colors.textDark,
    icon: "bed-outline",
    lib: "mci",
  },
  {
    key: "salle_attente",
    label: "Je suis dans la salle d'attente",
    bg: colors.yellow,
    textColor: colors.textDark,
    iconColor: colors.textDark,
    icon: "seat-outline",
    lib: "mci",
  },
  {
    key: "metro",
    label: "Je suis dans le métro",
    bg: colors.beige,
    textColor: colors.textDark,
    iconColor: colors.textDark,
    icon: "subway-variant",
    lib: "mci",
  },
  {
    key: "maison",
    label: "Je suis à la maison",
    bg: colors.offWhite,
    textColor: colors.textDark,
    iconColor: colors.textDark,
    icon: "home-outline",
    lib: "ion",
  },
];

function ContextIcon({ btn, size }: { btn: ContextButton; size: number }) {
  if (btn.lib === "ion") {
    return <Ionicons name={btn.icon as never} size={size} color={btn.iconColor} />;
  }
  return (
    <MaterialCommunityIcons name={btn.icon as never} size={size} color={btn.iconColor} />
  );
}

export default function Home() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const [profileChecked, setProfileChecked] = useState(false);

  useEffect(() => {
    api.getUserProfile()
      .then((profile) => {
        if (!profile) {
          // Types regenerated by Expo on next `expo start` — cast until then
          router.replace("/onboarding" as unknown as Href);
        } else {
          setProfileChecked(true);
        }
      })
      .catch(() => setProfileChecked(true));
  }, []);

  const onSelectContext = (btn: ContextButton) => {
    Haptics.selectionAsync();
    router.push({
      pathname: "/challenge",
      params: { context: btn.key, label: btn.label },
    });
  };

  if (!profileChecked) {
    return <View style={{ flex: 1, backgroundColor: colors.background }} />;
  }

  return (
    <View style={[styles.container, { paddingTop: insets.top }]} testID="home-screen">
      <View style={styles.header}>
        <TouchableOpacity onPress={() => supabase.auth.signOut()} hitSlop={8}>
          <DooLogo width={120} />
        </TouchableOpacity>
      </View>

      <Text style={styles.subtitle} testID="home-subtitle">
        Salut !{"\n"}Que se passe t-il autour de toi ?
      </Text>

      <ScrollView
        style={styles.list}
        contentContainerStyle={{ paddingBottom: insets.bottom + 94 }}
        showsVerticalScrollIndicator={false}
      >
        {CONTEXT_BUTTONS.map((btn, i) => (
          <Animated.View
            key={btn.key}
            entering={
              Platform.OS === "web" ? undefined : FadeInDown.delay(i * 70).springify()
            }
          >
            <TouchableOpacity
              activeOpacity={0.85}
              style={[styles.ctxButton, { backgroundColor: btn.bg }]}
              onPress={() => onSelectContext(btn)}
              testID={`context-button-${btn.key}`}
            >
              <Text style={[styles.ctxLabel, { color: btn.textColor }]}>{btn.label}</Text>
              <ContextIcon btn={btn} size={24} />
            </TouchableOpacity>
          </Animated.View>
        ))}
      </ScrollView>

      <BottomNav />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.lg,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
  },
  brand: {
    fontSize: 30,
    fontWeight: "800",
    color: colors.textPlum,
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: 18,
    lineHeight: 26,
    color: colors.textDark,
    marginBottom: spacing.lg,
    fontWeight: "500",
  },
  list: {
    flex: 1,
  },
  ctxButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 22,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    marginBottom: spacing.md,
    shadowColor: colors.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 2,
  },
  ctxLabel: {
    fontSize: 16,
    fontWeight: "600",
    flex: 1,
    marginRight: spacing.sm,
  },
});
